<div class="demo">
<p class="nav"><a href="#" onclick="$.galleria.prev(); return false;">&laquo; anterior</a> | <a href="#" onclick="$.galleria.next(); return false;">próxima &raquo;</a></p>

<div id="main_image"></div>
<ul class="gallery_demo">
    <?php
    $i = 0;
    foreach ($dados as $foto)
    { ?>
        <li <?php if($i == 0) echo 'class="active"' ?>><img src="template/images/fotos/<?php echo $foto['codProduto']. '.jpg'; ?>" alt="Rock" title="Legenda da primeira foto"></li>
    <?php
    $i++;
    }
    ?>
</ul>
</div>