<!-- BARRA DE TÍTULO -->
<div id="barraTitulo">
    <span class="legenda">Cadastro Pessoa Física</span>
</div> 


<div id="formPF"> 
    <form id="formulario" name="formulario" method="post" action="cadastropf.php"> 
        <div id="Form">
            <span class="tableRowGroup">
                <span class="TituloRel">Nome:</span>
                <br>
                <input name="nome" type="text" id="nome" style="width: 440px;">
            </span>
            <!-- Campo RG e CPF -->
            <span class="tableBlock">
                <span class="tableCell">
                    <span class="TituloRel">CPF:</span>
                    <br>
                    <input id="cpf" name="cpf" type="text" style="width: 220px;">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">RG:</span> 
                    <br>
                    <input name="rg" type="text" id="rg" style="width: 220px;">
                </span>                                
            </span>
            <!-- Campos E-mail e Data de Nascimento -->
            <span class="tableBlock">
                <span class="tableCell">
                    <span class="TituloRel">Email:</span>
                    <br> 
                    <input name="email" type="text" id="email" style="width: 220px">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">Data de Nascimento:</span>
                    <br>
                    <input name="dtNascimento" type="text" id="dtNascimento" style="width: 180px">
                </span>
            </span>
            <!-- Campos Endereço, número e complemento -->
            <span class="tableBlock">
                <span class="tableCell">
                    <span class="TituloRel">Endereço</span>
                    <br> 
                    <input name="endereco" type="text" id="endereco" style="width: 230px">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">N&#186;:</span>
                    <br>
                    <input name="numero" type="text" id="numero" style="width: 55px">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">Complemento:</span>
                    <br>
                    <input name="complemento" type="text" id="complemento" style="width: 80px">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">Cep:</span>
                    <br>
                    <input id="cep" name="cep" type="text" style="width: 70px">
                </span>
            </span>
            <!-- Campos Bairro, Cidade e Estado -->
            <span class="tableBlock">
                <span class="tableCell">
                    <span class="TituloRel">Bairro:</span>
                    <br>
                    <input name="bairro" type="text" id="bairro" style="width: 200px;">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">Cidade:</span>
                    <br>
                    <input name="cidade" type="text" id="cidade" style="width: 200px;">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">UF</span>
                    <br> 
                    <select name="estado" id="estado" style="width: 40px"> 
                        <option value=""></option>                        
                    </select>
                </span>
            </span>
            <!-- Campos Telefone 1, Telefone 2 e Celular -->
            <span class="tableBlock">
                <span class="tableCell">
                    <span class="TituloRel">Telefone 01:</span>
                    <br>
                    <input type="text" id="telefone1" name="tel1" style="width: 145px">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">Telefone 02:</span>
                    <br>
                    <input type="text" id="telefone2" name="tel2" style="width: 145px">
                </span>
                <span class="tableCell">
                    <span class="TituloRel">Celular:</span>
                    <br>
                    <input id="cel" name="cel" type="text" style="width: 145px" >
                </span>
            </span>
            <!-- Área de Texto -->
            <span class="tableBlock">
                <span class="TituloRel">Observações:</span>
                <br>
                <textarea class="msnBox" name="comentario" rows="5" style="width: 440px"></textarea>
            </span>
       </form> 	
    </div>
</div>