<!-- Importa os arquivos CSS -->
<link href="<?=DIR ?>template/css/cssGeral.css" rel="stylesheet" type="text/css" />
<link href="<?=DIR ?>template/css/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="<?=DIR ?>template/css/MenuPrincipalCss.css" rel="stylesheet" type="text/css" />
<link href="<?=DIR ?>template/css/<?php echo $controller ?>.css" rel="stylesheet" type="text/css" />

<!-- Importa os arquivos JQuery -->
<script type="text/javascript" src="<?=DIR ?>system/jquery/jquery.js"></script>
<script type="text/javascript" src="<?=DIR ?>system/jquery/jquery-ui.js"></script>
<script type="text/javascript" src="<?=DIR ?>system/jquery/maskedinput.js"></script>
<script type="text/javascript" src="<?=DIR ?>system/jquery/geral.js"></script>
<script type="text/javascript" src="<?=DIR ?>template/jquery/<?php echo $controller ?>.js"></script>
